---
settings:
  name: Announcements
  rss_page: index.html
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    lipi_enabled: false
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr
sidebar:
  entries:
  - title: Bienvenido
    url: "/index.html"
  - title: '2021'
    entries:
    - title: Documentos para la familia de productos Astra
      url: "/astra-family.html"
    - title: Documentos de Astra Data Store
      url: "/astra-data-store.html"
    - title: Documentos de Astra Trident
      url: "/astra-trident.html"
    - title: Documentos para Astra Control Center
      url: "/astra_control_center.html"
    - title: Rama predeterminada renombrada como principal
      url: "/default-branch-rename.html"
  - title: '2020'
    entries:
    - title: Actualización de documentos de NetApp HCI
      url: "/hci-update.html"
    - title: Descargar un PDF
      url: "/pdfs.html"
    - title: Mejor experiencia de usuario
      url: "/look-and-feel.html"
    - title: Documentos de ONTAP System Manager
      url: "/ontap-system-manager.html"
    - title: Documentos de cumplimiento de normativas en el cloud
      url: "/cloud-compliance.html"
    - title: Documentos de ONTAP Select
      url: "/ontap-select.html"
  - title: '2019'
    entries:
    - title: Documentos sobre soluciones y servicios cloud de NetApp HCI
      url: "/hci.html"
    - title: Guía de estilos y referencia de sintaxis
      url: "/style-and-syntax.html"
    - title: Docs para SaaS Backup para Salesforce
      url: "/salesforce.html"
    - title: Documentos de Active IQ
      url: "/active-iq.html"
    - title: RSS se alimenta en las nuevas páginas
      url: "/rss.html"
    - title: Documentos para la organización en niveles en el cloud
      url: "/cloud-tiering.html"
    - title: Avatares de GitHub para colaboradores
      url: "/avatars.html"
  - title: '2018'
    entries:
    - title: Resaltado de sintaxis
      url: "/syntax.html"
    - title: Navegación a nivel de página
      url: "/navigation.html"
    - title: Documentos de Converged Systems Advisor
      url: "/converged-systems-advisor.html"
    - title: Nueva forma de solicitar cambios en los documentos
      url: "/request-doc-changes.html"
    - title: Documentos de Cloud Insights
      url: "/cloud-insights.html"
    - title: Documentos de Cloud Volumes ONTAP
      url: "/cloud-volumes-ontap.html"
    - title: Documentos de Cloud Volumes Service para AWS
      url: "/cloud-volumes-service.html"
    - title: Docs de SaaS Backup para Office 365
      url: "/office365.html"
    - title: Presentamos documentos de NetApp en GitHub
      url: "/introduction.html"
